### PR TITLE
Update README.md with correct target flag for native Rust WebAssembly

### PR DESCRIPTION
**Pull request by anxiousmodernman**

### CODE REVIEW

**Comment by anxiousmodernman** [comment]
The context here was running `cargo web build --target=wasm32-unknown-unknown` yielded this error:
target

**Comment by Pauan** [comment]
Actually, the README is correct. It sounds like you're using an old version of `cargo-web`

Try running `cargo install --force cargo-web` to update `cargo-web`

**Comment by koute** [comment]
Yes, Pauan is correct. You're using an old version of `cargo-web`. I've recently changed the `--target-webasm` into `--target=wasm32-unknown-unknown` to be consistent with `cargo`.

**Comment by anxiousmodernman** [comment]
Ah, I should have tried upgrading first. The docs are up to date, as is. Thanks!

**Pull request closed without merging**
