### PR TITLE
Implement auto-reload using websockets

### PR DESCRIPTION
**Pull request by BenoitZugmeyer**
First of all, your project is amazing, thank you for doing this!

I managed to implement the auto-reload feature using Rouille websockets (I was quickly annoyed by the bazillion XHR showing in the devtools). I am not an expert in Rust, WebSocket and threading, so please review carefully.

I based my work on the [Condvar rust documentation examples](https://doc.rust-lang.org/std/sync/struct.Condvar.html) and the Rouille [websocket example](https://github.com/tomaka/rouille/blob/master/examples/websocket.rs).

### CODE REVIEW

**Comment by koute** [comment]
Thanks for the PR!

Hmm.. you know, I actually tried to do this using WebSockets initially, but the problem was that I was getting `The connection to ws://localhost:8000/__cargo_web__/ws was interrupted while the page was loading.` error, and I'm also seeing it with your PR, although for some reason... it seems works? (I'm using Firefox.)

Have you tried to use this websocket-based auto-refresh for a longer period of time?

**Comment by BenoitZugmeyer** [comment]
You are right, I didn't try it for a longer period. Maybe [closing](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#close()) the websocket before reloading the page would fix the error? I'll get back to you when I have time to work on it again.

**Comment by koute** [comment]
Well, I would certainly love to know *why* that error is generated, and *if* it's a problem or not. I'm assuming that there *should* be a way to do this without generating any errors.

At this point I'm not even sure if the problem is because we're using websockets wrong, or it is due to `rouille`'s implementation of the websockets. For example, is calling `next()` on the websocket to receive the messages from the client required with `rouille`? Does `rouille` automatically handle websocket pings if you don't call `next()`? Will the connection stay open forever if you don't receive any messages? (And you can't receive and send simultaneously with `rouille` since `next()` is blocking!) I don't know the answer to any of those questions.

It might be interesting to try to use another web server which supports websockets but is not `rouille` and see if it would fix the issue. Preferably just use `hyper` directly. In general I don't really care which exact framework we use for the embedded web server as long as it works. (And after yesterday's refactoring it should be even easier to replace `rouille` with another crate. Oh and, yeah, unfortunately the refactoring also created a bunch of conflicts with your PR. Sorry!)

So, to reiterate - I'd love to have the autorefresh use websockets, but I'd like to get rid of that error and be sure that the connection won't suddenly drop!

**Comment by BenoitZugmeyer** [comment]
Ok after further investigation, this error message comes after a refresh of the page, and it's actually the former websocket connection disconnecting (after about 30 seconds). It occurs only when the websocket "close" operation is not consumed by the server. And indeed, with my implementation, the operation is never consumed because it doesn't use `websocket.next()`.

So you were right, I don't think `rouille` websocket implementation is the right fit for this task. But I still want to help, so I'll try to replace `rouille` with `hyper` and use async websockets instead.

**Comment by koute** [comment]
> So you were right, I don't think `rouille` websocket implementation is the right fit for this task. But I still want to help, so I'll try to replace `rouille` with `hyper` and use async websockets instead.

Yep, that would be great!

**Pull request closed without merging**
