### PR TITLE
Add option to set chrome timeout

### LINKED ISSUE #209: Testing with chrome times out too fast
I get `error: tests timed out!` in the middle of the tests when running with chrome.

### PR DESCRIPTION
**Pull request by elichai**
Fixes #209 

Adding a timeout option for the chrome tests

### CODE REVIEW

**Comment by koute** [comment]
Thanks for the PR!

Hmm... instead of making the global timeout configurable here it'd probably just prefer to increase it significantly, and perhaps just add a warning if/when there is nothing printed out by the tests for a minute or two (kinda similar to what `cargo` itself does). Does that sound good to you?

**Comment by elichai** [comment]
sounds good. increasing the amount is fairly simple, to how long?

**Comment by koute** [comment]
How does, I don't know, 10 minutes sound? (We can always increase it further if anyone complains.)

**Comment by koute** [comment]
Closing since #212 was merged!

**Pull request closed without merging**
